version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: cptactionhank/atlassian-jira:latest 
    networks:
      - jira_network
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jira'
      - 'JIRA_DB_PASSWORD=pgpassword'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=2048m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    labels:
      com.blacklabelops.description: "iDalko Test Task Jira"
      com.blacklabelops.service: "jira"

  postgresql:
    image: postgres
    networks:
        internal_network:
             ipv4_address: 10.10.10.10 
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=pgpassword'
      - 'POSTGRES_DB=jira'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jira_network:
    driver: bridge
  internal_network:
    ipam:
      config:
        - subnet: 10.10.10.0/24
