version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: cptactionhank/atlassian-jira:latest 
    networks:
        internal_network:
             ipv4_address: 10.10.10.11 
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jira'
      - 'JIRA_DB_PASSWORD=pgpassword'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=2048m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='

  postgresql:
    image: postgres
    networks:
        internal_network:
             ipv4_address: 10.10.10.10 
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./iptables_update.sh
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=pgpassword'
      - 'POSTGRES_DB=jira'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

  nginx: 
    image: nginx:latest
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    networks:
      - jira_network
      - internal_network 
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jira_network:
    driver: bridge
  internal_network:
    ipam:
      config:
        - subnet: 10.10.10.0/24
